export { default as Login } from './login'
export { default as ViewArticle } from './view-article'
export { default as EditArticle } from './edit-article'
export { default as MyArticles } from './my-articles'
export { default as Home } from './home'
export { default as MyAccount } from './my-account'
