version: "3"

services:
  fboat-backend:
    image: fboat-backend
    container_name: fboat-backend
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      DB_HOST: db

  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
